### PR TITLE
Support new table elements in RNG schema

### PR DESCRIPTION
**Pull request by bertfrees**
@joeha480 Did I get it right? Tested the schema with the example OBFL file in Emacs.

### CODE REVIEW

**Comment by joeha480** [comment]
Thanks a lot!

**Comment by bertfrees** [comment]
Oh, I wasn't sure where table should be allowed. Only in sequence or also in block?

**Comment by joeha480** [comment]
Currently it is only allowed in sequence. Is that ok?

**Comment by bertfrees** [comment]
OK I think.

**Pull request merged**
